sudo: required
services:
  - docker

before_install:
  - docker build -t urfaevskii/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true urfaevskii/react-test npm run test -- --coverage

after_success:
  - docker build -t urfaevskii/multi-client ./client
  - docker build -t urfaevskii/multi-nginx ./nginx
  - docker build -t urfaevskii/multi-server ./server
  - docker build -t urfaevskii/multi-worker ./worker
  # Login to the docker CLI (docker login)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push urfaevskii/multi-client
  - docker push urfaevskii/multi-nginx
  - docker push urfaevskii/multi-server
  - docker push urfaevskii/multi-worker
