sudo: required
sevices:
  - docker

before_install:
  - docker build -t urfaevskii/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true urfaevskii/react-test npm run test -- --coverage

after_success:
  - docker build -t urfaevskii/multi-client -f ./client
  - docker build -t urfaevskii/multi-nginx -f ./nginx
  - docker build -t urfaevskii/multi-server -f ./server
  - docker build -t urfaevskii/multi-worker -f ./worker
  # Login to the docker CLI (docker login)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push urfaevskii/urfaevskii/multi-client
  - docker push urfaevskii/urfaevskii/multi-nginx
  - docker push urfaevskii/urfaevskii/multi-server
  - docker push urfaevskii/urfaevskii/multi-worker
